[spreadsheet]
# Insert Google API key https://console.cloud.google.com/apis/api/sheets.googleapis.com/
"api_key" = ""
# found between /d/ and /edit in url of a Google Sheets spreadsheet
"id" = "14f2IPkBaMliBQk7R9JWyQUCPs6u47kmug4BUyelVN7U"
"sheet" = "Queue"
# Row number to start from, indexing from 1
"row" = 3
# Column to scan, in letter notation
"column" = "C"

[wheel]
font = "Arial"
colors = [ # RGB arrays of colors to use for wedges; font colour will change to match
	[216,68,46],
	[113,222,64],
	[143,67,218],
	[217,215,50],
	[197,81,183],
	[156,195,75],
	[113,112,199],
	[215,140,44],
	[79,208,169],
	[195,82,139],
	[102,183,99],
	[200,73,95],
	[172,157,76],
	[184,95,61]
]
# Remove duplicate entries from the results; if false then entries will be combined
remove_dupes = false
# Suppress winner notification if handling visuals elsewhere
suppress_win = false
# How fast the wheel decelerates. 1.0 = -1% of current speed per tick
decel_rate = 1.0

[pointer] # Image that points to the result of the wheel
# Can be animated GIF or any other arbitrary image type
"file" = "pointer.png"
"scale" = 1.0
# Position on screen, adjustable for different images
"x_pos" = 1015
"y_pos" = 500

[center] # Image placed in the center of the wheel
# Can be animated GIF or any other arbitrary image type
"file" = "center.gif"
"scale" = 6.0
 # Rotate with the wheel
"rotate" = true

[tick] # Sound played when pointer 'hits' wedge
"file" = "tick.wav" # WAV only
"volume" = 1.0

[finished] # Sound played when wheel finishes spinning
"file" = "finished.wav" # WAV only
"volume" = 1.0

[window]
# Whether to use nearest neighbour scaling for pixel art sprites
nearest_neighbour = true

